Repository troop-370/troop370, pull requests merged in 2019-11, with the labels that each got.

#105 Hide & Disable Pine Straw
  _collections/_store/pinestraw.html
  index.html
Labels: priority: critical

#109 updates merit badge counselors to oct 2019
  _collections/_members/mb-counselors.html
Labels: enhancement

#110 Add November Campout 2019
  _collections/_members/campout-sign-up.html
  index.html
Labels: announcement, priority: high

#114 Add Adult Training section to Forms and Documents page
  _collections/_information/forms-documents.html
  index.html
  src/carousel-images/blackboard.jpg
  src/documents/Being A Merit Badge Counselor in Troop 370 (2019.11.06) R.pdf
Labels: enhancement, priority: high

#116 Update New Parent Handbook
  _collections/_about/about.html
  _collections/_information/forms-documents.html
  src/documents/New Parent Handbook 2017.pdf
  src/documents/New Parent Handbook 2019.pdf
Labels: enhancement, priority: medium

#120 Remove campout and contact info banners; show contact info update instructions in navigation
  _collections/_information/contact-info-directions.html
  index.html
Labels: enhancement, priority: high

#122 Add back required form elements for PayPal button on recharter page
  _collections/_payments/recharter.html
Labels: bug, priority: critical
