Repository troop-370/troop370, pull requests merged in 2019-03, with the labels that each got.

#36 Revamp particiation page to include more information about scout participation
  participation.html
Labels: enhancement, priority: low

#35 Create a communication information page with commuication methods and social media links
  _layouts/default.html
  communication_encrypted.html
  email-newsletters_encrypted.html
  service-worker.js
  styles/page-specific.css
Labels: enhancement, priority: medium

#38 Reorganize css to use variables (css custom properties)
  _layouts/default.html
  _layouts/encrypted.html
  resources/materialize/0.97.8/css/materialize-sidenav.css
  scripts/insert-header-footer.js
  service-worker.js
  src/index/370-mountains-dark.jpg
  styles/app.scss
  styles/bundle.css
  styles/colors.css
  styles/components-v2.css
  styles/fonts.css
  styles/index.css
  styles/page-specific.css
  styles/staticrypt.css
  styles/troop370-topnav-v2.css
Labels: enhancement, priority: low

#43 Add 2020 high adventure
  camps-adventure.html
  high-adventure-2020-sign-up_encrypted.html
  service-worker.js
Labels: enhancement

#52 Revamp submission sent page (appears after submitting a contact form)
  service-worker.js
  styles/checkmark.css
  submission-received.html
Labels: enhancement

#51 #47 fix
  service-worker.js
  styles/index.css
Labels: priority: critical

#55 Dark theme
  calendar_encrypted.html
  communication_encrypted.html
  mb-counselors_encrypted.html
  service-worker.js
  styles/colors.css
  styles/components-v2.css
  styles/troop370-topnav-v2.css
  troop-roster_encrypted.html
  what-can-i-do_encrypted.html
Labels: enhancement, priority: low
