Repository troop-370/troop370, pull requests merged in 2019-07, with the labels that each got.

#63 Troopmaster contact info update instructions
  contact-info-directions.html
  src/documents/Update your TroopMaster Contact Information.docx
  src/troopmaster-contact-info-instructions/pic1.png
  src/troopmaster-contact-info-instructions/pic2.png
  src/troopmaster-contact-info-instructions/pic3.png
  src/troopmaster-contact-info-instructions/pic4.png
  src/troopmaster-contact-info-instructions/step10.png
  src/troopmaster-contact-info-instructions/step7.png
  src/troopmaster-contact-info-instructions/step8.png
  src/troopmaster-contact-info-instructions/step9.png
  sw.js
Labels: priority: high

#72 Replace old cards with new cards for banquet and contact info
  banquet-sign-up.html
  index.html
  src/carousel-images/img_dinner_2x.jpg
Labels: enhancement

#73 Fall merit badge clinic 2019
  index.html
  merit-badge-clinic.html
  src/carousel-images/merit-badges.jpg
Labels: announcement, enhancement
